/*
 * FileName : request.http
 * ProjectName : ts-node
 * Author : terrorblade
 * Created Date: 2019-09-04 17:28:29
 * Description : 
 * -----
 * Last Modified: 2019-09-05 10:58:36
 * Modified By : 
 * -----
 * Copyright (c) 2019 芒果动听 Corporation. All rights reserved.
 */

###

POST http://localhost:8000/api/v1/user/addWxAppUser HTTP/1.1
Content-Type: application/json

{
	"openid":"asdadsasdsadaddasda",
	"avatarUrl":"asdadadadsadasdadadasda",
	"userName":"asdadsadadadasdadasdadasd",
	"gender":1,
	"school":"sadsadasdsadad",
	"gradeTime":"2014级",
	"departments":"院校",
	"specialty":"专业",
	"className":"班级",
	"iphone":"手机号",
	"email":"邮箱",
	"company":"公司名",
	"duty":"职业",
	"nowLive":"现居住地",
	"residentship":"原居住地"
}



